name: country_info_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  font_awesome_flutter: ^10.8.0
  http: ^1.3.0
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter



flutter:
  fonts:
    - family: Axiforma
      fonts:
        - asset: assets/font/Axiforma-Black.ttf
        - asset: assets/font/Axiforma-Bold.ttf
        - asset: assets/font/Axiforma-BoldItalic.ttf
        - asset: assets/font/Axiforma-Book.ttf
        - asset: assets/font/Axiforma-BookItalic.ttf
        - asset: assets/font/Axiforma-ExtraBold.ttf
        - asset: assets/font/Axiforma-ExtraBoldItalic.ttf
        - asset: assets/font/Axiforma-Heavy.ttf
        - asset: assets/font/Axiforma-HeavyItalic.ttf
        - asset: assets/font/Axiforma-Italic.ttf
        - asset: assets/font/Axiforma-Light.ttf
        - asset: assets/font/Axiforma-LightItalic.ttf
        - asset: assets/font/Axiforma-Medium.ttf
        - asset: assets/font/Axiforma-MediumItalic.ttf
        - asset: assets/font/Axiforma-Regular.ttf
        - asset: assets/font/Axiforma-SemiBold.ttf
        - asset: assets/font/Axiforma-Thin.ttf
          style: italic

  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
