import 'package:flutter_riverpod/flutter_riverpod.dart';

const Set<String> _languagesOptions = {
  "None",
  "English",
  "Swiss",
  "Romansh",
  "Hungarian",
  "Chinese",
  "Indonesian",
  "Lao",
  "Kirundi",
  "Southern",
  "Ndebele",
  "Northern",
  "Zulu",
  "Carolinian",
  "Macedonian",
  "Arabic",
  "French",
  "Guernésiais",
  "Faroese",
  "Uzbek",
  "Sinhala, Tamil",
  "Bengali",
  "Aymara, Quechua, Spanish",
  "English, Chinese, Malay, Tamil",
  "Dari, Pashto, Turkmen",
  "Dutch, Papiamento",
  "Cook Islands Māori",
  "Finnish",
  "Tokelauan",
  "Portuguese",
  "Upper Guinea Creole",
  "Azerbaijani",
  "Mauritian Creole",
  "Spanish",
  "Dutch",
  "Fijian",
  "Fiji Hindi",
  "German",
  "Nepali",
  "Georgian",
  "Urdu",
  "Hiri Motu",
  "Tok Pisin",
  "Norfuk",
  "Norwegian",
  "Malagasy",
  "Hindi",
  "Tamil",
  "Montenegrin",
  "Swazi",
  "Ukrainian",
  "Manx",
  "Afrikaans",
  "Herero",
  "Khoekhoe",
  "Kwangali",
  "Lozi",
  "Ndonga",
  "Tswana",
  "Bulgarian",
  "Greenlandic",
  "Khmer",
  "Aramaic",
  "Sorani",
  "Kyrgyz",
  "Russian",
  "Greek",
  "Turkish",
  "Chewa",
  "Bosnian",
  "Croatian",
  "Amharic",
  "Catalan",
  "Basque",
  "Galician",
  "Slovene",
  "Italian",
  "Sotho",
  "Marshallese",
  "Icelandic",
  "Luxembourgish",
  "Guaraní",
  "Nauru",
  "Berber",
  "Hassaniya",
  "Thai",
  "Haitian Creole",
  "Tuvaluan",
  "Belarusian",
  "Latvian",
  "Palauan",
  "Filipino",
  "Danish",
  "Tshiluba",
  "Swahili",
  "Somali",
  "Czech",
  "Bislama",
  "Niuean",
  "Kinyarwanda",
  "Estonian",
  "Tetum",
  "Vietnamese",
  "Latin",
  "Turkmen",
  "Irish",
  "Papiamento",
  "Nynorsk",
  "Bokmål",
  "Sami",
  "Sango",
  "Tigrinya",
  "Korean",
  "Lithuanian",
  "Slovak",
  "Kazakh",
  "Armenian",
  "Jèrriais",
  "Japanese",
  "Aymara",
  "Quechua",
  "Seychellois Creole",
  "Tajik",
  "Maltese",
  "Serbian",
  "Maldivian",
  "Persian",
  "Farsi",
  "Belizean Creole",
  "Burmese",
  "Dzongkha",
  "Jamaican Patois",
  "Polish",
  "Comorian",
  "Tongan",
  "Gilbertese",
  "Chibarwe",
  "Kalanga",
  "Khoisan",
  "Zimbabwean",
  "Mongolian",
  "Lingala",
  "Hebrew",
  "Māori",
  "New Zealand",
  "Sign Language",
};


final languagesOptionsProvider = Provider<Set<String>>((ref) {
  return _languagesOptions;
});